[package]
name = "nvtop"
version = "0.1.1"
edition = "2021"
description = """
`nvtop`: An NVIDIA SMI'esk GPU Monitoring tool for your terminal.

`nvtop` is a command-line utility that provides a replacement for some of the output from `nvidia-smi` (System Management Interface).
It offers real-time monitoring and visualization of GPU information: Core Clock, Temps, Fanspeed and Memory Usage.

# Usage:
```
# Monitor the GPU and system with a 1-second update interval
nvtop --delay 1000
```

"""
Keywords = [
  "Real-time monitoring",
  "GPU",
  "NVIDIA",
  "nvml",
  "nvidia-smi",
  "Command-line tool",
]
authors = ["jer, alphastrata@gmail.com"]
documentation = "https://www.github.com/alphastrata/nvtop"
license = "MIT"
homepage = "https://www.jeremyfwebb.ninja"
publish = true

[dependencies]
anyhow = "1.0.75"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
crossterm = "0.27.0"
csv = "1.3.0"
log = "0.4.20"
nvml-wrapper = "0.9.0"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
ratatui = "0.23.0"
thiserror = "1.0.49"
