name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Check for Clippy Warnings
      run: |
        # Run Clippy and capture its output
        CLIPPY_OUTPUT=$(cargo clippy --message-format json)

        # Check if Clippy produced any warnings
        if echo "$CLIPPY_OUTPUT" | jq -e '.reason | contains("warning")' > /dev/null; then
          echo "Clippy warnings found. This pull request will be denied."
          exit 1  # Set the workflow status to failed
        fi
